sudo: required
os: linux

language: python

python:
  - 3.7

services:
  - docker

before_script:
  - chmod +x docker_push.sh
  - chmod +x tests.sh

script:
  - docker-compose -f docker-compose_local.yml up -d
  - ./tests.sh
  - ./docker_push.sh
